// TOEIC 核心商業字彙題庫 - 200 個單字,分 5 大主題
// 每個字包含: id, word, pos(詞性), meaning(中文意思), example(例句), category

const VOCAB_CATEGORIES = {
  office: "辦公室日常",
  meetings: "會議簡報",
  hr: "人資求職",
  marketing: "行銷業務",
  travel: "差旅住宿"
};

const VOCAB_DATA = [
  // ---------------- office (辦公室日常) ----------------
  { id: 1, word: "colleague", pos: "n.", meaning: "同事", example: "I discussed the new policy with my colleague this morning.", category: "office" },
  { id: 2, word: "deadline", pos: "n.", meaning: "截止日期", example: "The deadline for the proposal is next Friday.", category: "office" },
  { id: 3, word: "agenda", pos: "n.", meaning: "議程", example: "Please review the agenda before the meeting starts.", category: "office" },
  { id: 4, word: "memo", pos: "n.", meaning: "備忘錄", example: "A memo was sent to all staff regarding the new dress code.", category: "office" },
  { id: 5, word: "supervisor", pos: "n.", meaning: "主管", example: "You should ask your supervisor for approval first.", category: "office" },
  { id: 6, word: "subordinate", pos: "n.", meaning: "下屬", example: "A good manager listens carefully to their subordinates.", category: "office" },
  { id: 7, word: "delegate", pos: "v.", meaning: "委派", example: "The director decided to delegate the task to a junior staff member.", category: "office" },
  { id: 8, word: "overtime", pos: "n.", meaning: "加班", example: "Employees who work overtime will receive extra pay.", category: "office" },
  { id: 9, word: "punctual", pos: "adj.", meaning: "準時的", example: "It is important to be punctual for client meetings.", category: "office" },
  { id: 10, word: "absent", pos: "adj.", meaning: "缺席的", example: "He was absent from work due to illness.", category: "office" },
  { id: 11, word: "attend", pos: "v.", meaning: "出席", example: "All department heads are required to attend the briefing.", category: "office" },
  { id: 12, word: "postpone", pos: "v.", meaning: "延後", example: "The meeting has been postponed until next week.", category: "office" },
  { id: 13, word: "reschedule", pos: "v.", meaning: "重新安排時間", example: "Could we reschedule our appointment to Thursday afternoon?", category: "office" },
  { id: 14, word: "cancel", pos: "v.", meaning: "取消", example: "The workshop was canceled due to low enrollment.", category: "office" },
  { id: 15, word: "confirm", pos: "v.", meaning: "確認", example: "Please confirm your attendance by replying to this email.", category: "office" },
  { id: 16, word: "notify", pos: "v.", meaning: "通知", example: "Staff will be notified of any schedule changes in advance.", category: "office" },
  { id: 17, word: "instruction", pos: "n.", meaning: "指示", example: "Follow the instructions carefully when filling out the form.", category: "office" },
  { id: 18, word: "supplies", pos: "n.", meaning: "用品", example: "Office supplies are stored in the cabinet near the entrance.", category: "office" },
  { id: 19, word: "equipment", pos: "n.", meaning: "設備", example: "New equipment was installed in the conference room.", category: "office" },
  { id: 20, word: "maintenance", pos: "n.", meaning: "維護", example: "The elevator is currently closed for maintenance.", category: "office" },
  { id: 21, word: "malfunction", pos: "n./v.", meaning: "故障", example: "The printer seems to be malfunctioning again.", category: "office" },
  { id: 22, word: "technician", pos: "n.", meaning: "技術人員", example: "A technician was called to repair the copy machine.", category: "office" },
  { id: 23, word: "install", pos: "v.", meaning: "安裝", example: "The IT department will install the new software this weekend.", category: "office" },
  { id: 24, word: "upgrade", pos: "v./n.", meaning: "升級", example: "We plan to upgrade all computers by the end of the year.", category: "office" },
  { id: 25, word: "photocopier", pos: "n.", meaning: "影印機", example: "The photocopier on the third floor is out of paper.", category: "office" },
  { id: 26, word: "stationery", pos: "n.", meaning: "文具", example: "You can find stationery in the supply closet.", category: "office" },
  { id: 27, word: "workspace", pos: "n.", meaning: "工作空間", example: "Employees are encouraged to keep their workspace tidy.", category: "office" },
  { id: 28, word: "relocate", pos: "v.", meaning: "搬遷", example: "The company will relocate its headquarters next spring.", category: "office" },
  { id: 29, word: "renovation", pos: "n.", meaning: "翻修", example: "The lobby is under renovation until further notice.", category: "office" },
  { id: 30, word: "facility", pos: "n.", meaning: "設施", example: "The new facility includes a fitness center for staff.", category: "office" },
  { id: 31, word: "procedure", pos: "n.", meaning: "程序", example: "Please follow the standard procedure when submitting expenses.", category: "office" },
  { id: 32, word: "policy", pos: "n.", meaning: "政策", example: "The company updated its remote work policy last month.", category: "office" },
  { id: 33, word: "regulation", pos: "n.", meaning: "規定", example: "All employees must comply with safety regulations.", category: "office" },
  { id: 34, word: "compliance", pos: "n.", meaning: "合規", example: "The audit confirmed the department's compliance with the law.", category: "office" },
  { id: 35, word: "confidential", pos: "adj.", meaning: "機密的", example: "This document contains confidential financial information.", category: "office" },
  { id: 36, word: "authorize", pos: "v.", meaning: "授權", example: "Only the manager can authorize this purchase.", category: "office" },
  { id: 37, word: "permit", pos: "n./v.", meaning: "許可", example: "You need a permit to park in this area.", category: "office" },
  { id: 38, word: "submit", pos: "v.", meaning: "提交", example: "Please submit your report by the end of the day.", category: "office" },
  { id: 39, word: "approve", pos: "v.", meaning: "批准", example: "The budget proposal was approved by the board.", category: "office" },
  { id: 40, word: "reject", pos: "v.", meaning: "拒絕", example: "The committee rejected the request for additional funding.", category: "office" },

  // ---------------- meetings (會議簡報) ----------------
  { id: 41, word: "conference", pos: "n.", meaning: "會議", example: "The annual conference will be held in Taipei this year.", category: "meetings" },
  { id: 42, word: "presentation", pos: "n.", meaning: "簡報", example: "She gave an excellent presentation on the new marketing strategy.", category: "meetings" },
  { id: 43, word: "participant", pos: "n.", meaning: "參與者", example: "Each participant will receive a certificate at the end of the seminar.", category: "meetings" },
  { id: 44, word: "venue", pos: "n.", meaning: "場地", example: "The venue for the conference has been changed to the downtown hotel.", category: "meetings" },
  { id: 45, word: "minutes", pos: "n.", meaning: "會議記錄", example: "The secretary will distribute the minutes after the meeting.", category: "meetings" },
  { id: 46, word: "proposal", pos: "n.", meaning: "提案", example: "The team submitted a proposal for the new product line.", category: "meetings" },
  { id: 47, word: "feedback", pos: "n.", meaning: "回饋", example: "We would appreciate your feedback on the presentation.", category: "meetings" },
  { id: 48, word: "handout", pos: "n.", meaning: "講義", example: "Handouts will be provided to all attendees.", category: "meetings" },
  { id: 49, word: "brainstorm", pos: "v.", meaning: "腦力激盪", example: "Let's brainstorm some ideas before the deadline.", category: "meetings" },
  { id: 50, word: "keynote speaker", pos: "n.", meaning: "主講人", example: "The keynote speaker discussed trends in digital marketing.", category: "meetings" },
  { id: 51, word: "schedule", pos: "n./v.", meaning: "時程表", example: "The meeting is scheduled for 10 a.m. on Monday.", category: "meetings" },
  { id: 52, word: "attendee", pos: "n.", meaning: "出席者", example: "Over two hundred attendees registered for the workshop.", category: "meetings" },
  { id: 53, word: "facilitate", pos: "v.", meaning: "促進", example: "The consultant was hired to facilitate the discussion.", category: "meetings" },
  { id: 54, word: "discussion", pos: "n.", meaning: "討論", example: "The discussion focused on ways to reduce costs.", category: "meetings" },
  { id: 55, word: "summary", pos: "n.", meaning: "摘要", example: "Please read the summary before the next session.", category: "meetings" },
  { id: 56, word: "outline", pos: "n.", meaning: "大綱", example: "She prepared an outline for her presentation.", category: "meetings" },
  { id: 57, word: "objective", pos: "n.", meaning: "目標", example: "The main objective of the meeting is to finalize the budget.", category: "meetings" },
  { id: 58, word: "session", pos: "n.", meaning: "場次", example: "The training session will last approximately two hours.", category: "meetings" },
  { id: 59, word: "panel", pos: "n.", meaning: "座談小組", example: "A panel of experts will answer questions after the talk.", category: "meetings" },
  { id: 60, word: "moderator", pos: "n.", meaning: "主持人", example: "The moderator introduced each speaker before their talk.", category: "meetings" },
  { id: 61, word: "audiovisual", pos: "adj.", meaning: "視聽的", example: "The audiovisual equipment needs to be tested before the event.", category: "meetings" },
  { id: 62, word: "projector", pos: "n.", meaning: "投影機", example: "The projector in the main hall is not working properly.", category: "meetings" },
  { id: 63, word: "microphone", pos: "n.", meaning: "麥克風", example: "Please speak closer to the microphone.", category: "meetings" },
  { id: 64, word: "teleconference", pos: "n.", meaning: "視訊會議", example: "We will hold a teleconference with the overseas branch tomorrow.", category: "meetings" },
  { id: 65, word: "videoconference", pos: "n.", meaning: "視訊會議", example: "The videoconference allowed both offices to join the discussion.", category: "meetings" },
  { id: 66, word: "RSVP", pos: "v.", meaning: "回覆是否出席", example: "Please RSVP by this Friday if you plan to attend.", category: "meetings" },
  { id: 67, word: "invitation", pos: "n.", meaning: "邀請函", example: "An invitation was sent to all shareholders.", category: "meetings" },
  { id: 68, word: "consensus", pos: "n.", meaning: "共識", example: "The board reached a consensus on the merger.", category: "meetings" },
  { id: 69, word: "vote", pos: "v./n.", meaning: "投票", example: "The members will vote on the proposal next week.", category: "meetings" },
  { id: 70, word: "resolution", pos: "n.", meaning: "決議", example: "The committee passed a resolution to increase the budget.", category: "meetings" },
  { id: 71, word: "adjourn", pos: "v.", meaning: "休會/散會", example: "The meeting was adjourned at noon.", category: "meetings" },
  { id: 72, word: "recap", pos: "v./n.", meaning: "摘要回顧", example: "Let's recap the main points before we finish.", category: "meetings" },
  { id: 73, word: "agenda item", pos: "n.", meaning: "議程項目", example: "The budget review is the first agenda item today.", category: "meetings" },
  { id: 74, word: "quorum", pos: "n.", meaning: "法定人數", example: "We cannot vote because we do not have a quorum.", category: "meetings" },
  { id: 75, word: "brief", pos: "v./adj.", meaning: "簡報/簡短的", example: "The manager will brief the team on the new procedures.", category: "meetings" },
  { id: 76, word: "clarify", pos: "v.", meaning: "澄清", example: "Could you clarify what you meant by that comment?", category: "meetings" },
  { id: 77, word: "elaborate", pos: "v.", meaning: "詳細說明", example: "Could you elaborate on the second point in your report?", category: "meetings" },
  { id: 78, word: "highlight", pos: "v.", meaning: "強調", example: "The report highlights several areas for improvement.", category: "meetings" },
  { id: 79, word: "address", pos: "v.", meaning: "談及/處理", example: "The CEO will address employee concerns during the town hall.", category: "meetings" },
  { id: 80, word: "wrap up", pos: "phr.", meaning: "結束/總結", example: "Let's wrap up the meeting with a quick summary.", category: "meetings" },

  // ---------------- hr (人資求職) ----------------
  { id: 81, word: "candidate", pos: "n.", meaning: "應徵者", example: "We interviewed five candidates for the marketing position.", category: "hr" },
  { id: 82, word: "résumé", pos: "n.", meaning: "履歷", example: "Please attach your résumé and cover letter to the application.", category: "hr" },
  { id: 83, word: "applicant", pos: "n.", meaning: "申請人", example: "All applicants must submit their forms by Friday.", category: "hr" },
  { id: 84, word: "interview", pos: "n./v.", meaning: "面試", example: "The final interview is scheduled for next Tuesday.", category: "hr" },
  { id: 85, word: "vacancy", pos: "n.", meaning: "職缺", example: "There is currently a vacancy in the accounting department.", category: "hr" },
  { id: 86, word: "recruit", pos: "v.", meaning: "招募", example: "The company plans to recruit ten new engineers this year.", category: "hr" },
  { id: 87, word: "hire", pos: "v.", meaning: "雇用", example: "We hired a new sales manager last month.", category: "hr" },
  { id: 88, word: "onboarding", pos: "n.", meaning: "新人培訓", example: "The onboarding process takes about one week.", category: "hr" },
  { id: 89, word: "orientation", pos: "n.", meaning: "職前訓練", example: "New employees must attend orientation on their first day.", category: "hr" },
  { id: 90, word: "probation", pos: "n.", meaning: "試用期", example: "New hires are on probation for the first three months.", category: "hr" },
  { id: 91, word: "qualification", pos: "n.", meaning: "資格", example: "The job requires a professional qualification in accounting.", category: "hr" },
  { id: 92, word: "reference", pos: "n.", meaning: "推薦人", example: "Please provide two professional references.", category: "hr" },
  { id: 93, word: "benefits", pos: "n.", meaning: "福利", example: "The position offers a competitive salary and excellent benefits.", category: "hr" },
  { id: 94, word: "salary", pos: "n.", meaning: "薪水", example: "Her starting salary was higher than expected.", category: "hr" },
  { id: 95, word: "compensation", pos: "n.", meaning: "薪酬", example: "The compensation package includes health insurance.", category: "hr" },
  { id: 96, word: "bonus", pos: "n.", meaning: "獎金", example: "Employees receive an annual bonus based on performance.", category: "hr" },
  { id: 97, word: "promotion", pos: "n.", meaning: "升遷", example: "She was offered a promotion after two years with the company.", category: "hr" },
  { id: 98, word: "appraisal", pos: "n.", meaning: "考核", example: "Performance appraisals are conducted twice a year.", category: "hr" },
  { id: 99, word: "performance review", pos: "n.", meaning: "績效考核", example: "Your performance review is scheduled for next Monday.", category: "hr" },
  { id: 100, word: "resign", pos: "v.", meaning: "辭職", example: "He decided to resign from his position last week.", category: "hr" },
  { id: 101, word: "retire", pos: "v.", meaning: "退休", example: "She plans to retire at the end of this year.", category: "hr" },
  { id: 102, word: "terminate", pos: "v.", meaning: "終止(雇用)", example: "The company terminated his contract due to budget cuts.", category: "hr" },
  { id: 103, word: "lay off", pos: "phr.", meaning: "裁員", example: "The factory had to lay off dozens of workers.", category: "hr" },
  { id: 104, word: "severance", pos: "n.", meaning: "資遣費", example: "Employees who were laid off received a severance package.", category: "hr" },
  { id: 105, word: "workforce", pos: "n.", meaning: "勞動力", example: "The company plans to expand its workforce next year.", category: "hr" },
  { id: 106, word: "staff", pos: "n.", meaning: "員工", example: "All staff are required to attend the training session.", category: "hr" },
  { id: 107, word: "personnel", pos: "n.", meaning: "人事", example: "Contact the personnel department for more information.", category: "hr" },
  { id: 108, word: "payroll", pos: "n.", meaning: "薪資名冊", example: "The payroll department processes salaries on the 25th of each month.", category: "hr" },
  { id: 109, word: "pension", pos: "n.", meaning: "退休金", example: "Employees contribute a portion of their salary to a pension fund.", category: "hr" },
  { id: 110, word: "leave of absence", pos: "n.", meaning: "請假", example: "She requested a leave of absence to care for her family.", category: "hr" },
  { id: 111, word: "sick leave", pos: "n.", meaning: "病假", example: "He took two days of sick leave last week.", category: "hr" },
  { id: 112, word: "maternity leave", pos: "n.", meaning: "產假", example: "She will begin her maternity leave next month.", category: "hr" },
  { id: 113, word: "shift", pos: "n.", meaning: "輪班", example: "The factory operates in three shifts around the clock.", category: "hr" },
  { id: 114, word: "part-time", pos: "adj.", meaning: "兼職的", example: "We are looking for a part-time assistant for the summer.", category: "hr" },
  { id: 115, word: "full-time", pos: "adj.", meaning: "全職的", example: "The internship may lead to a full-time position.", category: "hr" },
  { id: 116, word: "contract", pos: "n.", meaning: "合約", example: "Please read the contract carefully before signing.", category: "hr" },
  { id: 117, word: "eligible", pos: "adj.", meaning: "符合資格的", example: "Only full-time employees are eligible for this benefit.", category: "hr" },
  { id: 118, word: "skillset", pos: "n.", meaning: "技能組合", example: "Her skillset makes her a strong candidate for the role.", category: "hr" },
  { id: 119, word: "training program", pos: "n.", meaning: "培訓計畫", example: "New managers must complete a leadership training program.", category: "hr" },
  { id: 120, word: "supervise", pos: "v.", meaning: "監督", example: "She supervises a team of ten sales representatives.", category: "hr" },

  // ---------------- marketing (行銷業務) ----------------
  { id: 121, word: "advertisement", pos: "n.", meaning: "廣告", example: "The company placed an advertisement in the local newspaper.", category: "marketing" },
  { id: 122, word: "campaign", pos: "n.", meaning: "行銷活動", example: "The marketing campaign increased sales by twenty percent.", category: "marketing" },
  { id: 123, word: "target audience", pos: "n.", meaning: "目標客群", example: "The ad was designed to appeal to a younger target audience.", category: "marketing" },
  { id: 124, word: "consumer", pos: "n.", meaning: "消費者", example: "Consumer demand for eco-friendly products is increasing.", category: "marketing" },
  { id: 125, word: "retail", pos: "n./adj.", meaning: "零售", example: "The item's retail price is higher than its wholesale price.", category: "marketing" },
  { id: 126, word: "wholesale", pos: "n./adj.", meaning: "批發", example: "They sell electronics at wholesale prices to retailers.", category: "marketing" },
  { id: 127, word: "merchandise", pos: "n.", meaning: "商品", example: "All summer merchandise is now on sale.", category: "marketing" },
  { id: 128, word: "brand", pos: "n.", meaning: "品牌", example: "The company hopes to strengthen its brand image this year.", category: "marketing" },
  { id: 129, word: "logo", pos: "n.", meaning: "標誌", example: "The designer created a new logo for the product line.", category: "marketing" },
  { id: 130, word: "endorse", pos: "v.", meaning: "代言/背書", example: "The athlete was paid to endorse the sports brand.", category: "marketing" },
  { id: 131, word: "sponsor", pos: "v./n.", meaning: "贊助", example: "A local bank agreed to sponsor the charity event.", category: "marketing" },
  { id: 132, word: "launch", pos: "v./n.", meaning: "推出", example: "The company will launch its new product next month.", category: "marketing" },
  { id: 133, word: "promote", pos: "v.", meaning: "推廣", example: "Social media is an effective way to promote a new brand.", category: "marketing" },
  { id: 134, word: "discount", pos: "n.", meaning: "折扣", example: "Customers can get a 20 percent discount this weekend.", category: "marketing" },
  { id: 135, word: "coupon", pos: "n.", meaning: "優惠券", example: "You can use this coupon on your next purchase.", category: "marketing" },
  { id: 136, word: "complimentary", pos: "adj.", meaning: "免費贈送的", example: "Guests receive a complimentary drink upon arrival.", category: "marketing" },
  { id: 137, word: "survey", pos: "n.", meaning: "調查", example: "The company conducted a survey to measure customer satisfaction.", category: "marketing" },
  { id: 138, word: "questionnaire", pos: "n.", meaning: "問卷", example: "Please complete the questionnaire before you leave the store.", category: "marketing" },
  { id: 139, word: "satisfaction", pos: "n.", meaning: "滿意度", example: "Customer satisfaction has improved since the new policy began.", category: "marketing" },
  { id: 140, word: "complaint", pos: "n.", meaning: "抱怨", example: "The manager handled the customer's complaint professionally.", category: "marketing" },
  { id: 141, word: "warranty", pos: "n.", meaning: "保固", example: "The product comes with a one-year warranty.", category: "marketing" },
  { id: 142, word: "defective", pos: "adj.", meaning: "有瑕疵的", example: "Customers can return defective items for a full refund.", category: "marketing" },
  { id: 143, word: "replacement", pos: "n.", meaning: "替換品", example: "We will send a replacement free of charge.", category: "marketing" },
  { id: 144, word: "competitor", pos: "n.", meaning: "競爭對手", example: "Our main competitor just released a similar product.", category: "marketing" },
  { id: 145, word: "market share", pos: "n.", meaning: "市場佔有率", example: "The company's market share grew significantly this quarter.", category: "marketing" },
  { id: 146, word: "revenue", pos: "n.", meaning: "營收", example: "Annual revenue increased by fifteen percent.", category: "marketing" },
  { id: 147, word: "profit", pos: "n.", meaning: "利潤", example: "The firm reported a record profit this year.", category: "marketing" },
  { id: 148, word: "loss", pos: "n.", meaning: "虧損", example: "The company suffered a loss during the economic downturn.", category: "marketing" },
  { id: 149, word: "forecast", pos: "n./v.", meaning: "預測", example: "Analysts forecast steady growth for the next quarter.", category: "marketing" },
  { id: 150, word: "trend", pos: "n.", meaning: "趨勢", example: "The report identifies several key trends in the industry.", category: "marketing" },
  { id: 151, word: "demographic", pos: "n.", meaning: "人口統計特徵", example: "The campaign targets a specific demographic group.", category: "marketing" },
  { id: 152, word: "distribution", pos: "n.", meaning: "配銷", example: "The company expanded its distribution network overseas.", category: "marketing" },
  { id: 153, word: "supplier", pos: "n.", meaning: "供應商", example: "We changed suppliers to reduce production costs.", category: "marketing" },
  { id: 154, word: "vendor", pos: "n.", meaning: "賣方/供應商", example: "The vendor agreed to lower the price for bulk orders.", category: "marketing" },
  { id: 155, word: "client", pos: "n.", meaning: "客戶", example: "She met with an important client this afternoon.", category: "marketing" },
  { id: 156, word: "contract negotiation", pos: "n.", meaning: "合約協商", example: "The contract negotiation lasted several weeks.", category: "marketing" },
  { id: 157, word: "quote", pos: "n./v.", meaning: "報價", example: "Could you send us a quote for the printing job?", category: "marketing" },
  { id: 158, word: "invoice", pos: "n.", meaning: "發票/請款單", example: "Please pay the invoice within thirty days.", category: "marketing" },
  { id: 159, word: "purchase order", pos: "n.", meaning: "訂購單", example: "A purchase order must be approved before goods are shipped.", category: "marketing" },
  { id: 160, word: "transaction", pos: "n.", meaning: "交易", example: "All transactions are recorded in the accounting system.", category: "marketing" },

  // ---------------- travel (差旅住宿) ----------------
  { id: 161, word: "itinerary", pos: "n.", meaning: "行程表", example: "Please review your travel itinerary before departure.", category: "travel" },
  { id: 162, word: "reservation", pos: "n.", meaning: "預訂", example: "I would like to make a reservation for two nights.", category: "travel" },
  { id: 163, word: "accommodation", pos: "n.", meaning: "住宿", example: "The company will arrange accommodation for all conference guests.", category: "travel" },
  { id: 164, word: "boarding pass", pos: "n.", meaning: "登機證", example: "Please have your boarding pass ready at the gate.", category: "travel" },
  { id: 165, word: "departure", pos: "n.", meaning: "出發", example: "The departure time has been changed to 9 a.m.", category: "travel" },
  { id: 166, word: "arrival", pos: "n.", meaning: "抵達", example: "Please notify the hotel of your expected arrival time.", category: "travel" },
  { id: 167, word: "connecting flight", pos: "n.", meaning: "轉機航班", example: "She missed her connecting flight due to the delay.", category: "travel" },
  { id: 168, word: "layover", pos: "n.", meaning: "轉機停留", example: "We have a three-hour layover in Tokyo.", category: "travel" },
  { id: 169, word: "luggage", pos: "n.", meaning: "行李", example: "Please make sure your luggage meets the weight limit.", category: "travel" },
  { id: 170, word: "baggage claim", pos: "n.", meaning: "行李領取處", example: "You can pick up your suitcase at baggage claim.", category: "travel" },
  { id: 171, word: "customs", pos: "n.", meaning: "海關", example: "Travelers must go through customs before leaving the airport.", category: "travel" },
  { id: 172, word: "visa", pos: "n.", meaning: "簽證", example: "You will need a business visa to enter the country.", category: "travel" },
  { id: 173, word: "passport", pos: "n.", meaning: "護照", example: "Make sure your passport is valid for at least six months.", category: "travel" },
  { id: 174, word: "check in", pos: "phr.", meaning: "報到/入住登記", example: "Guests can check in after 3 p.m.", category: "travel" },
  { id: 175, word: "check out", pos: "phr.", meaning: "退房", example: "Please check out of your room by 11 a.m.", category: "travel" },
  { id: 176, word: "concierge", pos: "n.", meaning: "服務台人員", example: "The concierge helped us book a table at a nearby restaurant.", category: "travel" },
  { id: 177, word: "amenities", pos: "n.", meaning: "設施", example: "The hotel offers amenities such as a pool and gym.", category: "travel" },
  { id: 178, word: "complimentary breakfast", pos: "n.", meaning: "免費早餐", example: "A complimentary breakfast is included in the room rate.", category: "travel" },
  { id: 179, word: "shuttle bus", pos: "n.", meaning: "接駁車", example: "A shuttle bus runs between the hotel and the airport.", category: "travel" },
  { id: 180, word: "fare", pos: "n.", meaning: "票價", example: "The train fare increased slightly this year.", category: "travel" },
  { id: 181, word: "refund", pos: "n./v.", meaning: "退款", example: "You may request a refund if the flight is canceled.", category: "travel" },
  { id: 182, word: "reimbursement", pos: "n.", meaning: "報銷", example: "Submit your receipts for reimbursement within two weeks.", category: "travel" },
  { id: 183, word: "expense report", pos: "n.", meaning: "費用報告", example: "Please complete your expense report after the business trip.", category: "travel" },
  { id: 184, word: "per diem", pos: "n.", meaning: "每日津貼", example: "Employees receive a per diem to cover meals while traveling.", category: "travel" },
  { id: 185, word: "business trip", pos: "n.", meaning: "出差", example: "He is currently on a business trip to Singapore.", category: "travel" },
  { id: 186, word: "delay", pos: "n./v.", meaning: "延誤", example: "The flight was delayed due to bad weather.", category: "travel" },
  { id: 187, word: "cancellation", pos: "n.", meaning: "取消", example: "There is no fee for cancellation within 24 hours.", category: "travel" },
  { id: 188, word: "itemized", pos: "adj.", meaning: "逐項列出的", example: "Please request an itemized receipt from the hotel.", category: "travel" },
  { id: 189, word: "brochure", pos: "n.", meaning: "手冊", example: "The travel brochure lists several recommended tours.", category: "travel" },
  { id: 190, word: "destination", pos: "n.", meaning: "目的地", example: "Paris remains a popular destination for business travelers.", category: "travel" },
  { id: 191, word: "currency exchange", pos: "n.", meaning: "貨幣兌換", example: "You can find a currency exchange counter near the exit.", category: "travel" },
  { id: 192, word: "domestic", pos: "adj.", meaning: "國內的", example: "Domestic flights depart from Terminal 1.", category: "travel" },
  { id: 193, word: "overseas", pos: "adj.", meaning: "海外的", example: "She was promoted to manage the overseas branch.", category: "travel" },
  { id: 194, word: "round trip", pos: "n.", meaning: "來回行程", example: "A round trip ticket is often cheaper than two one-way tickets.", category: "travel" },
  { id: 195, word: "one-way", pos: "adj.", meaning: "單程的", example: "He booked a one-way ticket to New York.", category: "travel" },
  { id: 196, word: "terminal", pos: "n.", meaning: "航廈", example: "International flights depart from Terminal 2.", category: "travel" },
  { id: 197, word: "gate", pos: "n.", meaning: "登機門", example: "The flight will begin boarding at gate 14.", category: "travel" },
  { id: 198, word: "security check", pos: "n.", meaning: "安檢", example: "Passengers must go through a security check before boarding.", category: "travel" },
  { id: 199, word: "duty-free", pos: "adj.", meaning: "免稅的", example: "You can buy duty-free items after passing through security.", category: "travel" },
  { id: 200, word: "souvenir", pos: "n.", meaning: "紀念品", example: "She bought a souvenir for her colleague at the airport shop.", category: "travel" }
];
